name: Constructor

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies dotnet
        run: |
          sudo apt update
          sudo apt install dotnet-sdk-9.0
        continue-on-error: true
          
      - name: Install dependencies postgresql
        run: |
          sudo apt install -y postgresql-common
          sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
        continue-on-error: true
          
      - name: Install dependencies npm
        run: sudo npm install
        continue-on-error: true

      - name: Verify
        run: |
          sudo apt-get update
          dotnet --version
      - name: Verify2
        run: |
          sudo apt-get update
          dotnet --list-sdks
        continue-on-error: true
          
