name: Constructor

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:dotnet/backports
          
      - name: Install dependencies dotnet
        run: |
          sudo apt-get update && \
          sudo apt-get install -y dotnet-sdk-9.0
          
      - name: Install dependencies execute instants
        run: |
          sudo apt-get update && \
          sudo apt-get install -y dotnet-runtime-9.0
          
      - name: Install dependencies postgresql
        run: |
          sudo apt install -y postgresql-common
          sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
        continue-on-error: true
          
      - name: Install dependencies npm
        run: sudo npm install
        continue-on-error: true

      - name: Verify
        run: |
          dotnet --info
          dotnet --list-sdks
        continue-on-error: true
          
  tests_backend:
    needs: build
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./backend
    steps:
      - name: Check
        uses: actions/checkout@v4  
      - name: Allow Backend
        run: chmod +x setup_musictree.sh
      - name: Initialition Backend
        run: |
          ./setup_musictree.sh
          y
          .
        continue-on-error: true
      - name: Test Backend
        run: dotnet run
          
  tests_frontend:
    needs: tests_backend
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: musictree-frontend/
    steps:
      - name: Initialition Frontend
        run: |
          npm install
          npm run dev
          
