name: Constructor

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Add dependencies
        run: |
          sudo add-apt-repository ppa:dotnet/backports
          
      - name: Install dependencies dotnet
        run: |
          sudo add-apt-repository ppa:dotnet/backports
          sudo apt update
          sudo apt install dotnet-sdk-9.0=9.0.105-0ubuntu1~24.10.1
          
      - name: Install dependencies postgresql
        run: |
          sudo apt install -y postgresql-common
          sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
        continue-on-error: true
          
      - name: Install dependencies npm
        run: sudo npm install
        continue-on-error: true

      - name: Verify
        run: |
          sudo apt-get update
          dotnet --version
      - name: Verify2
        run: |
          sudo apt-get update
          dotnet --list-sdks
        continue-on-error: true
          
