name: Constructor

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies dotnet
        run: |
          sudo add-apt-repository ppa:dotnet/backports
          sudo apt update
          sudo apt install dotnet-sdk-9.0
        continue-on-error: true
          
      - name: Install dependencies postgresql
        run: |
          sudo apt install -y postgresql-common
          sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
        continue-on-error: true
          
      - name: Install dependencies npm
        run: sudo npm install
        continue-on-error: true

      - name: Update
        run: sudo apt-get update

      - name: Verify
        run: dotnet --version

      - name: Show
        run: dotnet --list-sdks

  tests_backend:
    needs: build
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./backend
    steps:
      - name: Check
        uses: actions/checkout@v4  
      - name: Allow Backend
        run: chmod +x setup_musictree.sh
      - name: Initialition Backend
        run: |
          ./setup_musictree.sh
          y
          .
        continue-on-error: true
      - name: Test Backend
        run: dotnet run
        continue-on-error: true
