name: Constructor

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Add dependencies
        run: |
          sudo add-apt-repository ppa:dotnet/backports
          
      - name: Install dependencies dotnet: Part1
        run: |
          sudo rm -rf /usr/share/dotnet
      - name: Part2
        run: |
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
      - name: Part3
        run: |
          chmod +x dotnet-install.sh
      - name: Part4
        run: |
          ./dotnet-install.sh --install-dir /usr/share/dotnet --version 9.0.105
      - name: Part5
        run: |
          export DOTNET_ROOT=/usr/lib/dotnet
      - name: Part6
        run: |
          export PATH=$DOTNET_ROOT:$PATH
      - name: Part7
        run: |
          source ~/.bashrc
      - name: Part8
        run: |
          dotnet --list-sdks
          
      - name: Install dependencies postgresql
        run: |
          sudo apt install -y postgresql-common
          sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
        continue-on-error: true
          
      - name: Install dependencies npm
        run: sudo npm install
        continue-on-error: true

      - name: Verify
        run: |
          sudo apt-get update
          dotnet --list-sdks
        continue-on-error: true
          
