name: Constructor

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get remove 'dotnet*' 'aspnet*' 'netstandard*'

          wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          rm packages-microsoft-prod.deb
          sudo apt-get update

          sudo apt-get install -y dotnet-host-8.0
      - name: Install dependencies dotnet
        run: |
          sudo apt-get update
          sudo apt-get update && \
          sudo apt-get install -y dotnet-sdk-9.0
          
      - name: Install dependencies postgresql
        run: |
          sudo apt install -y postgresql-common
          sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
        continue-on-error: true
          
      - name: Install dependencies npm
        run: sudo npm install
        continue-on-error: true
          
  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Initialition Backend
        working-directory: backend/
        run: |
          setup_musictree.sh
          y
          .
          dotnet run
          
      - name: Initialition Frontend
        working-directory: musictree-frontend/
        run: |
          npm install
          npm run dev
          
