name: Constructor

on:
  push:
  pull_request:

jobs:
  tests_backend:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./backend
    steps:
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.107
      - name: Allow Backend
        run: chmod +x setup_musictree.sh
        continue-on-error: true
        
      - name: Initialition Backend
        run: |
          ./setup_musictree.sh
          y
          .
        continue-on-error: true
      - name: Test Backend
        run: dotnet run
        continue-on-error: true
